/*
CREATED		22/03/2022
MODIFIED		27/04/2022
PROJECT		
MODEL		
COMPANY		
AUTHOR		
VERSION		
DATABASE		MYSQL 5 
*/


DROP TABLE IF EXISTS ASIGNATURA_ESTUDIO;
DROP TABLE IF EXISTS NOTA;
DROP TABLE IF EXISTS ESTUDIO;
DROP TABLE IF EXISTS CENTROS;
DROP TABLE IF EXISTS ASIGNATURA;
DROP TABLE IF EXISTS ALUMNOS;
DROP TABLE IF EXISTS HISTORIAL_ACADEMICO;


CREATE TABLE HISTORIAL_ACADEMICO (
	CODIGO_HISTORIAL_ACADEMICO CHAR(8) NOT NULL,
	NUMERO_ALUMNO CHAR(5) NOT NULL,
	CODIGO_ESTUDIO CHAR(4) NOT NULL,
	ANIO_PRIMER_ESTUDIO YEAR(4) NOT NULL,
	ANIO_ULTIMO_ESTUDIO YEAR(4) NOT NULL,
	CURSO_ACADEMICO YEAR(4) NOT NULL,
	CALIFICACION_FINAL_ORDINARIA DOUBLE NOT NULL,
	CALIFICACION_FINAL_EXTRAORDINARIA DOUBLE NOT NULL,
	NUMERO_CONVOCATORIA_ASIGNATURA INT NOT NULL,
 PRIMARY KEY (CODIGO_HISTORIAL_ACADEMICO)) ENGINE = INNODB;

CREATE TABLE ALUMNOS (
	NUMERO_ALUMNO CHAR(5) NOT NULL,
	VECES_REPETIDO INT NOT NULL,
	DNI_ALUMNO CHAR(9) NOT NULL,
	NOMBRE_ALUMNO VARCHAR(20) NOT NULL,
	APELLIDO1_ALUMNO VARCHAR(20) NOT NULL,
	APELLIDO2_ALUMNO VARCHAR(15) NOT NULL,
	FECHA_NACIMIENTO_ALUMNO DATE NOT NULL,
	DIRECCION_ALUMNO VARCHAR(50) NOT NULL,
	TELEFONO_ALUMNO CHAR(9) NOT NULL,
 PRIMARY KEY (NUMERO_ALUMNO)) ENGINE = INNODB;

CREATE TABLE ASIGNATURA (
	CODIGO_ASIGNATURA CHAR(4) NOT NULL,
	NOMBRE_ASIGNATURA VARCHAR(50) NOT NULL,
	CONVALIDACION_ASIGNATURA CHAR(4) NOT NULL,
 PRIMARY KEY (CODIGO_ASIGNATURA)) ENGINE = INNODB;

CREATE TABLE CENTROS (
	CODIGO_CENTRO CHAR(8) NOT NULL,
	NOMBRE_CENTRO VARCHAR(50) NOT NULL,
	DIRECCION_CENTRO VARCHAR(75) NOT NULL,
	CP_CENTRO CHAR(5) NOT NULL,
 PRIMARY KEY (CODIGO_CENTRO)) ENGINE = INNODB;

CREATE TABLE ESTUDIO (
	CODIGO_ESTUDIO CHAR(4) NOT NULL,
	CODIGO_CENTRO CHAR(5) NOT NULL,
	ETAPA_ESTUDIO VARCHAR(20) NOT NULL COMMENT 'PRIMARIA
SECUNDARIA
BACHILLERATO
FPB
FPGM
FPGS
UNIVERSIDAD',
	NOMBRE_ESTUDIO VARCHAR(50) NOT NULL,
 PRIMARY KEY (CODIGO_ESTUDIO)) ENGINE = INNODB;

CREATE TABLE NOTA (
	NUMERO_ALUMNO CHAR(5) NOT NULL,
	CODIGO_ASIGNATURA CHAR(4) NOT NULL,
	NOTA DOUBLE NOT NULL,
 PRIMARY KEY (NUMERO_ALUMNO,CODIGO_ASIGNATURA,NOTA)) ENGINE = INNODB;

CREATE TABLE ASIGNATURA_ESTUDIO (
	CODIGO_ASIGNATURA CHAR(4) NOT NULL,
	CODIGO_ESTUDIO CHAR(4) NOT NULL,
	HORAS_ASIGNATURA_ESTUDIO INT NOT NULL,
 PRIMARY KEY (CODIGO_ASIGNATURA,CODIGO_ESTUDIO)) ENGINE = INNODB;


ALTER TABLE HISTORIAL_ACADEMICO ADD FOREIGN KEY (NUMERO_ALUMNO) REFERENCES ALUMNOS (NUMERO_ALUMNO) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE NOTA ADD FOREIGN KEY (NUMERO_ALUMNO) REFERENCES ALUMNOS (NUMERO_ALUMNO) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE NOTA ADD FOREIGN KEY (CODIGO_ASIGNATURA) REFERENCES ASIGNATURA (CODIGO_ASIGNATURA) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE ASIGNATURA_ESTUDIO ADD FOREIGN KEY (CODIGO_ASIGNATURA) REFERENCES ASIGNATURA (CODIGO_ASIGNATURA) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE ESTUDIO ADD FOREIGN KEY (CODIGO_CENTRO) REFERENCES CENTROS (CODIGO_CENTRO) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE HISTORIAL_ACADEMICO ADD FOREIGN KEY (CODIGO_ESTUDIO) REFERENCES ESTUDIO (CODIGO_ESTUDIO) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE ASIGNATURA_ESTUDIO ADD FOREIGN KEY (CODIGO_ESTUDIO) REFERENCES ESTUDIO (CODIGO_ESTUDIO) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
--etapas estudio
INSERT INTO ESTUDIO VALUES('0301','28045815','Bachillerato','1ºBachillerato_Ciencias_Sociales_y_Humanidades')
INSERT INTO ESTUDIO VALUES('0302,'28045815','Bachillerato','2ºBachillerato_Ciencias_Sociales_y_Humanidades')

INSERT INTO ESTUDIO VALUES('2001','28045815','Secundaria','1ºEducacion_secundaria_obligatoria')
INSERT INTO ESTUDIO VALUES('2002','28045815','Secundaria','2ºEducacion_secundaria_obligatoria')
INSERT INTO ESTUDIO VALUES('2003','28045815','Secundaria','3ºEducacion_secundaria_obligatoria')
INSERT INTO ESTUDIO VALUES('2004','28045815','Secundaria','4ºEducacion_secundaria_obligatoria')


INSERT INTO ESTUDIO VALUES('1001','28056126','Primaria','1ºEducacion_primaria_obligatoria')
INSERT INTO ESTUDIO VALUES('1002','28056126','Primaria','2ºEducacion_primaria_obligatoria')
INSERT INTO ESTUDIO VALUES('1003','28056126','Primaria','3ºEducacion_primaria_obligatoria')
INSERT INTO ESTUDIO VALUES('1004','28056126','Primaria','4ºEducacion_primaria_obligatoria')
INSERT INTO ESTUDIO VALUES('1005','28056126','Primaria','5ºEducacion_primaria_obligatoria')
INSERT INTO ESTUDIO VALUES('1006','28056126','Primaria','6ºEducacion_primaria_obligatoria')


INSERT INTO ESTUDIO VALUES('4001','28039827','FPGS','1ºDesarrollo_de_aplicaciones_multiplataforma')
INSERT INTO ESTUDIO VALUES('4002','28039827','FPGM','1º Sistemas Microinformaticos en Red')

--centros
INSERT INTO CENTROS VALUES('28045815','IES_AVALON','C. Dalí,50,28342 Valdemoro,Madrid''28340')
INSERT INTO CENTROS VALUES('28056126','CEIP_PedroAntonio_De_Alarcon','Calle Artemisa, s/n''28340')
INSERT INTO CENTROS VALUES('28039827','IES_LAGUNA_DE_JOATZEL','Av. de las Vascongadas, s/n,Getafe, Madrid','28903')

--asignatura_estudio
--primaria
--1º
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1001','1001',840)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1002','1001',545)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1003','1001',480)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1004','1001',480)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1005','1001',365)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1006','1001',300)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1007','1001',210)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1008','1001',210)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1009','1001',360)
--2º

INSERT INTO ASIGNATURA_ESTUDIO VALUES('1010','1002',840)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1011','1002',545)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1012','1002',480)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1013','1002',480)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1014','1002',365)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1015','1002',300)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1016','1002',210)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1017','1002',210)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1018','1002',360)

--3º
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1019','1003',840)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1020','1003',545)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1021','1003',480)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1022','1003',480)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1023','1003',365)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1034','1003',300)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1025','1003',210)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1026','1003',210)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1027','1003',360)

--4º

INSERT INTO ASIGNATURA_ESTUDIO VALUES('1028','1004',840)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1029','1004',545)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1030','1004',480)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1031','1004',480)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1032','1004',365)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1033','1004',300)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1034','1004',210)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1035','1004',210)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1036','1004',360)

--5º

INSERT INTO ASIGNATURA_ESTUDIO VALUES('1037','1005',840)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1038','1005',545)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1039','1005',480)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1040','1005',480)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1041','1005',365)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1042','1005',300)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1043','1005',210)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1044','1005',210)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1045','1005',360)

--6º


INSERT INTO ASIGNATURA_ESTUDIO VALUES('1046','1006',840)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1047','1006',545)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1048','1006',480)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1049','1006',480)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1050','1006',365)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1051','1006',300)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1052','1006',210)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1053','1006',210)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('1054','1006',360)


--ESO
--1º

INSERT INTO ASIGNATURA_ESTUDIO VALUES('2001','2001',840)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2002','2001',545)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2003','2001',840)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2004','2001',545)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2005','2001',365)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2006','2001',300)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2007','2001',210)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2008','2001',210)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2009','2001',360)

--2º

INSERT INTO ASIGNATURA_ESTUDIO VALUES('2010','2002',840)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2011','2002',545)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2012','2002',840)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2013','2002',545)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2014','2002',365)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2015','2002',300)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2016','2002',210)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2017','2002',210)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2018','2002',360)

--3º
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2019','2003',840)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2020','2003',545)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2022','2003',840)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2023','2003',545)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2024','2003',365)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2025','2003',300)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2026','2003',210)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2027','2003',210)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2028','2003',360)

--4º

INSERT INTO ASIGNATURA_ESTUDIO VALUES('2029','2004',840)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2030','2004',545)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2031','2004',840)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2032','2004',545)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2033','2004',365)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2034','2004',300)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2035','2004',210)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2036','2004',210)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('2037','2004',360)

--Bachillerato

--1º
INSERT INTO ASIGNATURA_ESTUDIO VALUES('3001','3001',365)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('3002','3001',545)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('3003','3001',210)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('3004','3001',840)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('3005','3001',840)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('3006','3001',300)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('3007','3001',545)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('3008','3001',210)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('3009','3001',210)

--2º
INSERT INTO ASIGNATURA_ESTUDIO VALUES('3010','3002',365)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('3011','3002',545)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('3012','3002',545)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('3013','3002',210)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('3014','3002',365)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('3015','3002',300)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('3016','3002',210)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('3017','3002',840)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('3018','3002',545)

--1ºDAM
INSERT INTO ASIGNATURA_ESTUDIO VALUES('4001','4001',230)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('4002','4001',170)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('4003','4001',90)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('4004','4001',120)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('4005','4001',170)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('4006','4001',90)
--SMR 
INSERT INTO ASIGNATURA_ESTUDIO VALUES('4007','FPGM',200)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('4008','FPGM',200)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('4009','FPGM',270)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('4010','FPGM',170)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('4011','FPGM',240)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('4012','FPGM',85)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('4013','FPGM',170)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('4014','FPGM',100)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('4015','FPGM',90)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('4016','FPGM',65)
INSERT INTO ASIGNATURA_ESTUDIO VALUES('4017','FPGM',370)



--asignaturas 1ºPrimaria

INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1001', 'Lengua Castellana y Literatura1', '1001'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1002', 'Matematicas1', '1002'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1003', 'Ciencias de la naturaleza1', '1003'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1004', 'Ciencias Sociales1', '1004'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1005', 'Primera lengua extranjera1', '1005'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1006', 'Educacion física', '1006'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1007', 'Religion', '1007'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1008', 'Valores eticos', '1008'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1009', 'Educacion artística', '1009'),

--asignaturas 2ºprimaria

INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1010', 'Lengua Castellana y Literatura2', '1010'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1011', 'Matematicas2', '1011'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1012', 'Ciencias de la naturaleza2', '1012'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1013', 'Ciencias Sociales2', '1013'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1014', 'Primera lengua extranjera2', '1014'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1015', 'Educacion física2', '1015'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1016', 'Religion2', '1016'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1017', 'Valores eticos2', '1017'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1018', 'Educacion artística2', '1018'),

--asignaturas 3ºprimaria


INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1019', 'Lengua Castellana y Literatura3', '1019'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1020', 'Matematicas3', '1020'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1021', 'Ciencias de la naturaleza3', '1021'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1022', 'Ciencias Sociales3', '1022'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1023', 'Primera lengua extranjera3', '1023'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1024', 'Educacion física3', '1024'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1025', 'Religion3', '1025'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1026', 'Valores eticos3', '1026'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1027', 'Educacion artística3', '1027'),


--asignaturas 4º primaria


INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1028', 'Lengua Castellana y Literatura4', '1028'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1029', 'Matematicas4', '1029'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1030', 'Ciencias de la naturaleza4', '1030'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1031', 'Ciencias Sociales4', '1031'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1032', 'Primera lengua extranjera4', '1032'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1033', 'Educacion física4', '1033'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1034', 'Religion4', '1034'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1035', 'Valores eticos4', '1035'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1036', 'Educacion artística4', '1036'),

--asignaturas 5º de primaria


INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1037', 'Lengua Castellana y Literatura5', '1037'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1038', 'Matematicas5', '1038'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1039', 'Ciencias de la naturaleza5', '1039'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1040', 'Ciencias Sociales5', '1040'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1041', 'Primera lengua extranjera5', '1041'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1042', 'Educacion física5', '1042'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1043', 'Religion5', '1043'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1044', 'Valores eticos5', '1044'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1045', 'Educacion artística5', '1045'),


--asignaturas 6º de primaria


INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1046', 'Lengua Castellana y Literatura6', '1046'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1047', 'Matematicas6', '1047'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1048', 'Ciencias de la naturaleza6', '1048'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1049', 'Ciencias Sociales6', '1049'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1050', 'Primera lengua extranjera6', '1050'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1051', 'Educacion física6', '1051'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1052', 'Religion6', '1052'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1053', 'Valores eticos6', '1053'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('1054', 'Educacion artística6', '1054'),


--asignaturas 1ºESO
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2001', 'Biología y Geología', '2001'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2002', 'Geografía e Historia', '2002'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2003', 'Lengua Castellana y Literatura', '2003'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2004', 'Matemáticas', '2004'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2005', 'Primera Lengua Extranjera', '2005'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2006', 'Segunda Lengua Extranjera', '2006'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2007', 'Valores Eticos', '2007'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2008', 'Educacion Fisica', '2008'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2009', 'Tecnologia', '2009'),

--asignaturas 2ºESO
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2010', 'Biología y Geología2', '2010'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2011', 'Geografía e Historia2', '2011'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2012', 'Lengua Castellana y Literatura2', '2012'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2013', 'Matemáticas2', '2013'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2014', 'Primera Lengua Extranjera2', '2014'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2015', 'Tecnologia2', '2015'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2016', 'Valores Eticos2', '2016'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2017', 'Educacion Fisica2', '2017'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2018', 'Segunda Lengua Extranjera2', '2018'),

--asignaturas 3ºESO 
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2019','Biología y Geología3', '2019'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2020', 'Geografía e Historia3', '2020'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2022', 'Lengua Castellana y Literatura3', '2022'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2023', 'Matemáticas3', '2023'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2024', 'Primera Lengua Extranjera3', '2024'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2025', 'Tecnologia3', '2025'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2026', 'Valores Eticos3', '2026'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2027', 'Educacion Fisica3', '2027'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2028', 'Segunda Lengua Extranjera3', '2028'),

--asignaturas 4ºESO

INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2029', 'Geografía e Historia4', '2029'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2030', 'Lengua Castellana y Literatura4', '2030'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2031', 'Primera Lengua Extranjera4', '2031'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2032', 'Matemáticas Orientadas a las Enseñanzas Académicas', '2032'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2033', 'Economía', '2033'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2034', 'Latín', '2034'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2035', 'Tecnologías de la Información y la Comunicación', '2035'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2036', 'Educación Física4', '2036'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('2037', 'Valores Eticos4', '2037'),


--asignaturas 1ºbach
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('3001', 'Economia', 'ECO01', '3001'),
('3002', 'Filosofia', 'FLS01', '3002'),
('3003', 'Educacion Fisica ', 'EF01', '3003'),
('3004', 'LenguaCastellanaLite', 'LCYL01', '3004'),
('3005', 'Matemáticas Aplicada', 'MAACS01', '3005'),
('3006', 'Literatura Universal', 'LU01', '3006'),
('3007', 'Lengua Extranjera ', 'LE01', '3007'),
('3008', 'Tecnologia InfyCom ', 'TIC01', '3008'),
('3009', 'Cultura Científica ', 'CC01', '3009');
--asignaturas 2ºbach
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('3010', 'Economía de la Empresa', '3010'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('3011', 'Geografía ', '3011'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('3012', 'Historia de la Filosofía ', '3012'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('3013', 'Psicología ', 'PSIC02', '3013'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('3014', 'Lengua Extranjera II: Francés  ','3014'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('3015', 'Tecnologías de la Información y la Comunicación II ', '3015'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('3016', 'LenguaCastellanaLite', '3016'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('3017', 'Matemáticas Aplicadas a las Ciencias Sociales II', '3017'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('3018', 'Hstoria de España', '3018'),

--asignaturas DAM1

INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('4001', 'Programacion', '4001'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('4002', 'Bases de datos', '4002'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('4003', 'Entornos de desarrollo', '4003'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('4004', 'Lenguaje de marcas', '4004'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('4005', 'Sistemas informaticos', '4005'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('4006', 'Formacion y orientacion laboral', '4006'),

--asignaturas SMR
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('4007', 'Montaje y mantenimiento de equipo', '4007'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('4008', 'Sistemas operativos monopuesto', '4008'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('4009', 'Aplicaciones ofimáticas', '4009'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('4010', 'Sistemas operativos en red', '4010'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('4011', 'Redes locales', '4011'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('4012', 'Seguridad informatica', '4012'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('4013', 'Servicios en red', '4013'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('4014', 'Aplicaciones web', '4014'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('4015', 'Formación y orientación laboral', '4015'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('4016', 'Empresa e iniciativa empresarial', '4016'),
INSERT INTO `asignatura` (`CODIGO_ASIGNATURA`, `NOMBRE_ASIGNATURA`, `CONVALIDACION_ASIGNATURAS`) VALUES
('4017', 'Formación en centros de trabajo', '4017'),









INSERT INTO ALUMNOS VALUES('00002','0','01948303L','Aaron','Borrego','Maganto','27-01-2001','C/AnaFrank_nº3-Valdemoro-Madrid','662370800')
INSERT INTO ALUMNOS VALUES('00003','1','01042302G','Diego','Garcia','DeLasOlivas','22-03-2002','C/MariaDelCarmen-Villaverde','661546730')


